// shadcn/ui pages with named exports
export { Dashboard } from './Dashboard';
export { WorkloadGiangVien } from './WorkloadGiangVien';
export { GroupOverviewManagement } from './GroupOverviewManagement';
export { SemesterManagement } from './SemesterManagement';
export { TemplateManagement } from './TemplateManagement';
export { LecturerManagement } from './LecturerManagement';
export { StudentManagement } from './StudentManagement';
export { CourseManagement } from './CourseManagement';
